version: '3.8'

services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/code
    environment:
      HOST: "${HOST}" 
      PORT: "${PORT}" 
      CONSUMER_KEY: "${CONSUMER_KEY}"
      CONSUMER_SECRET: "${CONSUMER_SECRET}"
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      FLASK_ENV: "${FLASK_ENV}" 
      # MONGO_HOST: "${MONGO_HOST}"
      # MONGO_PORT: "${MONGO_PORT}"
    depends_on:
      - database
  database:
    image: postgres
    container_name: onibsb-bot-db
    restart: always
    # TODO remove ports when app is containerized
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=onibsb-bot
    volumes:
      - pgdata:/data/postgres
    # TODO uncomment network_mode when app is containerized
    # network_mode: host
volumes:
  pgdata:
    driver: local